[package]
name = "facebook-permission"
version = "0.1.0"
edition = "2018"

[dependencies]
serde-enum-str = { version = "0.1.1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
