[package]
name = "facebook-fb-login-deauth-callback-warp"
version = "0.1.0"
edition = "2018"

[dependencies]
facebook-fb-login-deauth-callback = { path = "../..", version = "=0.1.0" }

warp = { version = "0.3", default-features = false }
