[package]
name = "facebook-permission-html_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = { version = "0.15" }
selectors = { version = "0.24" }
convert_case = { version = "0.6" }
