[package]
name = "facebook-webhook-warp"
version = "0.1.0"
edition = "2018"

[dependencies]
facebook-webhook = { path = "../..", version = "=0.1.0" }

warp = { version = "0.3", default-features = false }
bytes = { version = "1.0", default-features = false }
